### ISSUE TITLE
Colored graph for tibber

### ISSUE THREAD

**Issue by 6thGuest** [edwardtfn/HomeAssistant-Config#1]
Hey Edward,
since I am totally unexperienced in programming I had to use "copy-paste" and "try-and-error" for integrating the tibber price graphs into HA.
I only used your rest-sensor:
```
sensor:
    # https://community.home-assistant.io/t/tibber-sensor-for-future-price-tomorrow/253818/23
    - platform: rest
      name: Tibber Electricity Price
      resource: https://api.tibber.com/v1-beta/gql
      method: POST
      scan_interval: 900
      payload: '{ "query": "{ viewer { homes { currentSubscription { priceInfo { current { total currency level } today { total startsAt level } tomorrow { total startsAt level }}}}}}" }'
      json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
      json_attributes:
        - current
        - today
        - tomorrow
      value_template: '{{ value_json["data"]["viewer"]["homes"][0]["currentSubscription"]["priceInfo"]["current"]["total"] }}'
      headers:
        Authorization: !secret tibber_api_token
        Content-Type: application/json
        User-Agent: REST
```
It also states "Cheap, normal and expensive".

![tibber_prices](https://user-images.githubusercontent.com/124683921/222708224-4aba0084-f2fa-4c80-a1fa-8c71f9be2aff.jpg)

Now I wonder if it is possible to create a line or bar chart with the different colors for it.
E.g. cheap=green, normal=yellow and expensive=red and/or a sensor which states the times with the cheapest prices maybe like this:
"Cheapest today: 01:00:00 - 02:00:00
                             15:00:00 - 16:00:00"
"Cheapest tomorrow: 07:00:00 - 08:00:00"

Do you think it is possible to create something like this?

THANKS so far!
