### ISSUE TITLE
HA updates everything.

### ISSUE THREAD

**Issue by cociweb** [edwardtfn/HomeAssistant-Config#17]
Hello,

I've use your blueprint to update HA&it's companion.

In my automation, I've use this setup:
![image](https://github.com/user-attachments/assets/54b156b0-5763-4d39-a312-19e6304ed8e7)

once a time, a module update came out which required the latest ha core, and it throw me an error: to let's update the core to the required version first, then the automation stopped the execution after backup.

I've check the trace and it turned out, that it would like to update everything (while I've only selected the Core and OS only):

```
_Executed: 2024. november 23. 14:17:41
Result:
params:
  domain: homeassistant
  service: update_entity
  service_data: {}
  target:
    entity_id:
      - update.home_assistant_supervisor_update
      - update.home_assistant_core_update
      - update.samba_share_update
      - update.log_viewer_update
      - .......tones of update.xyz entities......_
```

STEP CONFIG:
```
alias: Refresh update list - update entities
action: homeassistant.update_entity
data: {}
target:
  entity_id: '{{ states.update | map(attribute=''entity_id'') | list }}'
continue_on_error: true
```

I had the same with v2024.9.5.2 but also with v2024.9.30.0.
